version: '3.9'

services:
  eventstore:
    image: eventstore/eventstore:21.10.5-buster-slim
    container_name: eventstore
    networks:
      - order-service
    restart: unless-stopped
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  db:
    image: mongo
    container_name: db
    networks:
      - order-service
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

networks:
  order-service:

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  db-data: